version: "3.8"

services:
  gov_xian:
    build: .
    environment:
      - GOV_MODULE=gov_xian
      - MODULE_URL=https://zjj.xa.gov.cn/zxcx/gczj/indexHis.aspx?page=1&qdm=ZZXU
      - REPORTS_DIR=config
      - API_KEY=app-P5fQM2owKecAABbKhp0qnwcA
      - API_HOST=http://dify-api-1:5001
    ipc: host
    networks:
      - elastic
    volumes:
      - ./app:/app
    ports:
      - "8900:8900"

networks:
  elastic:
    external: true